<?php
    include '../../controller/systemcore.php'; 
    $systemcore = new systemcore();
    $System_Sessioning = $systemcore->System_Sessioning("session");
    $count = 1;
    $SelectGroups = $systemcore->SelectTable("vaccine_registration WHERE time_stamp = '2021-10-8'");
    foreach($SelectGroups as $value){  
        $employmentcategory = $value["employmentcategory"];
        $sub_category = $value["sub_category"];
        $idcategory = $value["idcategory"];
        $idnumber = $value["idnumber"];
        $phid = $value["phid"];
        $pwdid = $value["pwdid"];
        $lastname = $value["lastname"];
        $firstname = $value["firstname"];
        $middlename = $value["middlename"];
        $suffix = $value["suffix"];
        $contact = $value["contact"];
        $gender = $value["gender"];
        $bday = $value["bday"];
        $brgy = $value["brgy"];
        $region = $value["region"];
        $province = $value["province"];
        $city = $value["city"];
        $civil_status = $value["civil_status"];
        $employment_status = $value["employment_status"];
        $ocupation = $value["ocupation"];
        $agency = $value["agency"];
        $current_residence = $value["current_residence"];
        $pregnant = $value["pregnant"];
        $covid_status = $value["covid_status"];
        $covid_exposure = $value["covid_exposure"];
        $reason_refusal = $value["reason_refusal"];
        $if_severe_allergic = $value["if_severe_allergic"];
        $allergy = $value["allergy"];
        $if_allergy = $value["if_allergy"];
        $dose_1 = $value["dose_1"];
        $dose_2 = $value["dose_2"];
        $allergies_to_PEG = $value["allergies_to_PEG"];
        $bleeding_disorders = $value["bleeding_disorders"];
        $if_bleeding = $value["if_bleeding"];
        $symtoms = $value["symtoms"];
        $if_receive_vaccine = $value["if_receive_vaccine"];
        $comorbidity = $value["comorbidity"];
        $consent = $value["consent"];
        $defferal = $value["defferal"];
        $time_stamp = $value["time_stamp"];
        $convalescent = $value["convalescent"];
        $if_pregnant = $value["if_pregnant"];
        $vaccine_name = $value["vaccine_name"];
        $batch_number = $value["batch_number"];
        $lot_number = $value["lot_number"];
        $vaccinator_name = $value["vaccinator_name"];
        $prof_vaccinator = $value["prof_vaccinator"];
        $medical_clearance = $value["medical_clearance"];
        $allergy_to_vaccine = $value["allergy_to_vaccine"];
        $profile_comorbidity = $value["profile_comorbidity"];
        $qr_id = $value["qr_id"];
        $encoded = $value["encoded"];
        $indigenous = $value["indigenous"];
        $pwd = $value["pwd"];
        $adverse_event = $value["adverse_event"];
        $adverse_event_cons = $value["adverse_event_cons"];
        $encoded_by = $value["encoded_by"];
        $facility_id = $value["facility_id"];

        $table = "local_data_fetcher";
        $table_col = "employmentcategory, sub_category, idcategory, idnumber, phid, pwdid, lastname, firstname, middlename, suffix, contact, gender, bday, brgy, region, province, city, civil_status, employment_status, ocupation, agency, current_residence, pregnant, covid_status, covid_exposure, reason_refusal, if_severe_allergic, allergy, if_allergy, dose_1, dose_2, allergies_to_PEG, bleeding_disorders, if_bleeding, symtoms, if_receive_vaccine, comorbidity, consent, defferal, time_stamp, convalescent, if_pregnant, vaccine_name, batch_number, lot_number, vaccinator_name, prof_vaccinator, medical_clearance, allergy_to_vaccine, profile_comorbidity, qr_id, encoded, indigenous, pwd, adverse_event, adverse_event_cons, encoded_by, facility_id";
        $table_val = "'$employmentcategory', '$sub_category', '$idcategory', '$idnumber', '$phid', '$pwdid', '$lastname', '$firstname', '$middlename', '$suffix', '$contact', '$gender', '$bday', '$brgy', '$region', '$province', '$city', '$civil_status', '$employment_status', '$ocupation', '$agency', '$current_residence', '$pregnant', '$covid_status', '$covid_exposure', '$reason_refusal', '$if_severe_allergic', '$allergy', '$if_allergy', '$dose_1', '$dose_2', '$allergies_to_PEG', '$bleeding_disorders', '$if_bleeding', '$symtoms', '$if_receive_vaccine', '$comorbidity', '$consent', '$defferal', '$time_stamp', '$convalescent', '$if_pregnant', '$vaccine_name', '$batch_number', '$lot_number', '$vaccinator_name', '$prof_vaccinator', '$medical_clearance', '$allergy_to_vaccine', '$profile_comorbidity', '$qr_id', '$encoded', '$indigenous', '$pwd', '$adverse_event', '$adverse_event_cons', '$encoded_by', '$facility_id'"; 
        $InsertTable = $systemcore->InsertTable($table, $table_col, $table_val);
    }
?>