
<?php
    // 150 names
    $array_f_name = array('Allison',    'Arthur',    'Ana',    'Alex',    'Arlene',    'Alberto',    'Barry',    'Bertha',    'Bill',    'Bonnie',    'Bret',    'Beryl',    'Chantal',    'Cristobal',    'Claudette',    'Charley',    'Cindy',    'Chris',    'Dean',    'Dolly',    'Danny',
    'Danielle',    'Dennis',
    'Debby',    'Erin',    'Edouard',    'Erika',    'Earl',    'Emily',    'Ernesto',
    'Felix',    'Fay',    'Fabian',    'Frances',    'Franklin',    'Florence',    'Gabielle',    'Gustav',    'Grace',    'Gaston',    'Gert',    'Gordon',    'Humberto',    'Hanna',    'Henri',    'Hermine',    'Harvey',    'Helene',    'Iris','Isidore','Isabel','Ivan','Irene','Isaac','Jerry',
    'Josephine','Juan','Jeanne','Jose','Joyce','Karen','Kyle','Kate','Karl','Katrina','Kirk','Lorenzo','Lili','Larry','Lisa','Lee',
    'Leslie','Michelle','Marco','Mindy','Maria','Michael','Noel','Nana','Nicholas','Nicole','Nate','Nadine','Olga','Omar','Odette','Otto','Ophelia','Oscar','Pablo','Paloma','Peter','Paula','Philippe',
    'Patty','Rebekah','Rene','Rose','Richard','Rita','Rafael','Sebastien','Sally','Sam','Shary','Stan','Sandy','Tanya','Teddy','Teresa','Tomas','Tammy','Tony','Van',
    'Vicky','Victor','Virginie','Vince','Valerie','Wendy','Wilfred','Wanda','Walter','Wilma','William','Kumiko','Aki','Miharu','Chiaki','Michiyo','Itoe','Nanaho','Reina',
    'Emi','Yumi','Ayumi','Kaori','Sayuri','Rie','Miyuki','Hitomi','Naoko','Miwa','Etsuko','Akane','Kazuko','Miyako','Youko','Sachiko','Mieko','Toshie','Junko');
    //1000
    $array_last_names = array(
        'Abbott',
        'Acevedo',
        'Acosta',
        'Adams',
        'Adkins',
        'Aguilar',
        'Aguirre',
        'Albert',
        'Alexander',
        'Alford',
        'Allen',
        'Allison',
        'Alston',
        'Alvarado',
        'Alvarez',
        'Anderson',
        'Andrews',
        'Anthony',
        'Armstrong',
        'Arnold',
        'Ashley',
        'Atkins',
        'Atkinson',
        'Austin',
        'Avery',
        'Avila',
        'Ayala',
        'Ayers',
        'Bailey',
        'Baird',
        'Baker',
        'Baldwin',
        'Ball',
        'Ballard',
        'Banks',
        'Barber',
        'Barker',
        'Barlow',
        'Barnes',
        'Barnett',
        'Barr',
        'Barrera',
        'Barrett',
        'Barron',
        'Barry',
        'Bartlett',
        'Barton',
        'Bass',
        'Bates',
        'Battle',
        'Bauer',
        'Baxter',
        'Beach',
        'Bean',
        'Beard',
        'Beasley',
        'Beck',
        'Becker',
        'Bell',
        'Bender',
        'Benjamin',
        'Bennett',
        'Benson',
        'Bentley',
        'Benton',
        'Berg',
        'Berger',
        'Bernard',
        'Berry',
        'Best',
        'Bird',
        'Bishop',
        'Black',
        'Blackburn',
        'Blackwell',
        'Blair',
        'Blake',
        'Blanchard',
        'Blankenship',
        'Blevins',
        'Bolton',
        'Bond',
        'Bonner',
        'Booker',
        'Boone',
        'Booth',
        'Bowen',
        'Bowers',
        'Bowman',
        'Boyd',
        'Boyer',
        'Boyle',
        'Bradford',
        'Bradley',
        'Bradshaw',
        'Brady',
        'Branch',
        'Bray',
        'Brennan',
        'Brewer',
        'Bridges',
        'Briggs',
        'Bright',
        'Britt',
        'Brock',
        'Brooks',
        'Brown',
        'Browning',
        'Bruce',
        'Bryan',
        'Bryant',
        'Buchanan',
        'Buck',
        'Buckley',
        'Buckner',
        'Bullock',
        'Burch',
        'Burgess',
        'Burke',
        'Burks',
        'Burnett',
        'Burns',
        'Burris',
        'Burt',
        'Burton',
        'Bush',
        'Butler',
        'Byers',
        'Byrd',
        'Cabrera',
        'Cain',
        'Calderon',
        'Caldwell',
        'Calhoun',
        'Callahan',
        'Camacho',
        'Cameron',
        'Campbell',
        'Campos',
        'Cannon',
        'Cantrell',
        'Cantu',
        'Cardenas',
        'Carey',
        'Carlson',
        'Carney',
        'Carpenter',
        'Carr',
        'Carrillo',
        'Carroll',
        'Carson',
        'Carter',
        'Carver',
        'Case',
        'Casey',
        'Cash',
        'Castaneda',
        'Castillo',
        'Castro',
        'Cervantes',
        'Chambers',
        'Chan',
        'Chandler',
        'Chaney',
        'Chang',
        'Chapman',
        'Charles',
        'Chase',
        'Chavez',
        'Chen',
        'Cherry',
        'Christensen',
        'Christian',
        'Church',
        'Clark',
        'Clarke',
        'Clay',
        'Clayton',
        'Clements',
        'Clemons',
        'Cleveland',
        'Cline',
        'Cobb',
        'Cochran',
        'Coffey',
        'Cohen',
        'Cole',
        'Coleman',
        'Collier',
        'Collins',
        'Colon',
        'Combs',
        'Compton',
        'Conley',
        'Conner',
        'Conrad',
        'Contreras',
        'Conway',
        'Cook',
        'Cooke',
        'Cooley',
        'Cooper',
        'Copeland',
        'Cortez',
        'Cote',
        'Cotton',
        'Cox',
        'Craft',
        'Craig',
        'Crane',
        'Crawford',
        'Crosby',
        'Cross',
        'Cruz',
        'Cummings',
        'Cunningham',
        'Curry',
        'Curtis',
        'Dale',
        'Dalton',
        'Daniel',
        'Daniels',
        'Daugherty',
        'Davenport',
        'David',
        'Davidson',
        'Davis',
        'Dawson',
        'Day',
        'Dean',
        'Decker',
        'Dejesus',
        'Delacruz',
        'Delaney',
        'Deleon',
        'Delgado',
        'Dennis',
        'Diaz',
        'Dickerson',
        'Dickson',
        'Dillard',
        'Dillon',
        'Dixon',
        'Dodson',
        'Dominguez',
        'Donaldson',
        'Donovan',
        'Dorsey',
        'Dotson',
        'Douglas',
        'Downs',
        'Doyle',
        'Drake',
        'Dudley',
        'Duffy',
        'Duke',
        'Duncan',
        'Dunlap',
        'Dunn',
        'Duran',
        'Durham',
        'Dyer',
        'Eaton',
        'Edwards',
        'Elliott',
        'Ellis',
        'Ellison',
        'Emerson',
        'England',
        'English',
        'Erickson',
        'Espinoza',
        'Estes',
        'Estrada',
        'Evans',
        'Everett',
        'Ewing',
        'Farley',
        'Farmer',
        'Farrell',
        'Faulkner',
        'Ferguson',
        'Fernandez',
        'Ferrell',
        'Fields',
        'Figueroa',
        'Finch',
        'Finley',
        'Fischer',
        'Fisher',
        'Fitzgerald',
        'Fitzpatrick',
        'Fleming',
        'Fletcher',
        'Flores',
        'Flowers',
        'Floyd',
        'Flynn',
        'Foley',
        'Forbes',
        'Ford',
        'Foreman',
        'Foster',
        'Fowler',
        'Fox',
        'Francis',
        'Franco',
        'Frank',
        'Franklin',
        'Franks',
        'Frazier',
        'Frederick',
        'Freeman',
        'French',
        'Frost',
        'Fry',
        'Frye',
        'Fuentes',
        'Fuller',
        'Fulton',
        'Gaines',
        'Gallagher',
        'Gallegos',
        'Galloway',
        'Gamble',
        'Garcia',
        'Gardner',
        'Garner',
        'Garrett',
        'Garrison',
        'Garza',
        'Gates',
        'Gay',
        'Gentry',
        'George',
        'Gibbs',
        'Gibson',
        'Gilbert',
        'Giles',
        'Gill',
        'Gillespie',
        'Gilliam',
        'Gilmore',
        'Glass',
        'Glenn',
        'Glover',
        'Goff',
        'Golden',
        'Gomez',
        'Gonzales',
        'Gonzalez',
        'Good',
        'Goodman',
        'Goodwin',
        'Gordon',
        'Gould',
        'Graham',
        'Grant',
        'Graves',
        'Gray',
        'Green',
        'Greene',
        'Greer',
        'Gregory',
        'Griffin',
        'Griffith',
        'Grimes',
        'Gross',
        'Guerra',
        'Guerrero',
        'Guthrie',
        'Gutierrez',
        'Guy',
        'Guzman',
        'Hahn',
        'Hale',
        'Haley',
        'Hall',
        'Hamilton',
        'Hammond',
        'Hampton',
        'Hancock',
        'Haney',
        'Hansen',
        'Hanson',
        'Hardin',
        'Harding',
        'Hardy',
        'Harmon',
        'Harper',
        'Harrell',
        'Harrington',
        'Harris',
        'Harrison',
        'Hart',
        'Hartman',
        'Harvey',
        'Hatfield',
        'Hawkins',
        'Hayden',
        'Hayes',
        'Haynes',
        'Hays',
        'Head',
        'Heath',
        'Hebert',
        'Henderson',
        'Hendricks',
        'Hendrix',
        'Henry',
        'Hensley',
        'Henson',
        'Herman',
        'Hernandez',
        'Herrera',
        'Herring',
        'Hess',
        'Hester',
        'Hewitt',
        'Hickman',
        'Hicks',
        'Higgins',
        'Hill',
        'Hines',
        'Hinton',
        'Hobbs',
        'Hodge',
        'Hodges',
        'Hoffman',
        'Hogan',
        'Holcomb',
        'Holden',
        'Holder',
        'Holland',
        'Holloway',
        'Holman',
        'Holmes',
        'Holt',
        'Hood',
        'Hooper',
        'Hoover',
        'Hopkins',
        'Hopper',
        'Horn',
        'Horne',
        'Horton',
        'House',
        'Houston',
        'Howard',
        'Howe',
        'Howell',
        'Hubbard',
        'Huber',
        'Hudson',
        'Huff',
        'Huffman',
        'Hughes',
        'Hull',
        'Humphrey',
        'Hunt',
        'Hunter',
        'Hurley',
        'Hurst',
        'Hutchinson',
        'Hyde',
        'Ingram',
        'Irwin',
        'Jackson',
        'Jacobs',
        'Jacobson',
        'James',
        'Jarvis',
        'Jefferson',
        'Jenkins',
        'Jennings',
        'Jensen',
        'Jimenez',
        'Johns',
        'Johnson',
        'Johnston',
        'Jones',
        'Jordan',
        'Joseph',
        'Joyce',
        'Joyner',
        'Juarez',
        'Justice',
        'Kane',
        'Kaufman',
        'Keith',
        'Keller',
        'Kelley',
        'Kelly',
        'Kemp',
        'Kennedy',
        'Kent',
        'Kerr',
        'Key',
        'Kidd',
        'Kim',
        'King',
        'Kinney',
        'Kirby',
        'Kirk',
        'Kirkland',
        'Klein',
        'Kline',
        'Knapp',
        'Knight',
        'Knowles',
        'Knox',
        'Koch',
        'Kramer',
        'Lamb',
        'Lambert',
        'Lancaster',
        'Landry',
        'Lane',
        'Lang',
        'Langley',
        'Lara',
        'Larsen',
        'Larson',
        'Lawrence',
        'Lawson',
        'Le',
        'Leach',
        'Leblanc',
        'Lee',
        'Leon',
        'Leonard',
        'Lester',
        'Levine',
        'Levy',
        'Lewis',
        'Lindsay',
        'Lindsey',
        'Little',
        'Livingston',
        'Lloyd',
        'Logan',
        'Long',
        'Lopez',
        'Lott',
        'Love',
        'Lowe',
        'Lowery',
        'Lucas',
        'Luna',
        'Lynch',
        'Lynn',
        'Lyons',
        'Macdonald',
        'Macias',
        'Mack',
        'Madden',
        'Maddox',
        'Maldonado',
        'Malone',
        'Mann',
        'Manning',
        'Marks',
        'Marquez',
        'Marsh',
        'Marshall',
        'Martin',
        'Martinez',
        'Mason',
        'Massey',
        'Mathews',
        'Mathis',
        'Matthews',
        'Maxwell',
        'May',
        'Mayer',
        'Maynard',
        'Mayo',
        'Mays',
        'Mcbride',
        'Mccall',
        'Mccarthy',
        'Mccarty',
        'Mcclain',
        'Mcclure',
        'Mcconnell',
        'Mccormick',
        'Mccoy',
        'Mccray',
        'Mccullough',
        'Mcdaniel',
        'Mcdonald',
        'Mcdowell',
        'Mcfadden',
        'Mcfarland',
        'Mcgee',
        'Mcgowan',
        'Mcguire',
        'Mcintosh',
        'Mcintyre',
        'Mckay',
        'Mckee',
        'Mckenzie',
        'Mckinney',
        'Mcknight',
        'Mclaughlin',
        'Mclean',
        'Mcleod',
        'Mcmahon',
        'Mcmillan',
        'Mcneil',
        'Mcpherson',
        'Meadows',
        'Medina',
        'Mejia',
        'Melendez',
        'Melton',
        'Mendez',
        'Mendoza',
        'Mercado',
        'Mercer',
        'Merrill',
        'Merritt',
        'Meyer',
        'Meyers',
        'Michael',
        'Middleton',
        'Miles',
        'Miller',
        'Mills',
        'Miranda',
        'Mitchell',
        'Molina',
        'Monroe',
        'Montgomery',
        'Montoya',
        'Moody',
        'Moon',
        'Mooney',
        'Moore',
        'Morales',
        'Moran',
        'Moreno',
        'Morgan',
        'Morin',
        'Morris',
        'Morrison',
        'Morrow',
        'Morse',
        'Morton',
        'Moses',
        'Mosley',
        'Moss',
        'Mueller',
        'Mullen',
        'Mullins',
        'Munoz',
        'Murphy',
        'Murray',
        'Myers',
        'Nash',
        'Navarro',
        'Neal',
        'Nelson',
        'Newman',
        'Newton',
        'Nguyen',
        'Nichols',
        'Nicholson',
        'Nielsen',
        'Nieves',
        'Nixon',
        'Noble',
        'Noel',
        'Nolan',
        'Norman',
        'Norris',
        'Norton',
        'Nunez',
        'Obrien',
        'Ochoa',
        'Oconnor',
        'Odom',
        'Odonnell',
        'Oliver',
        'Olsen',
        'Olson',
        'Oneal',
        'Oneil',
        'Oneill',
        'Orr',
        'Ortega',
        'Ortiz',
        'Osborn',
        'Osborne',
        'Owen',
        'Owens',
        'Pace',
        'Pacheco',
        'Padilla',
        'Page',
        'Palmer',
        'Park',
        'Parker',
        'Parks',
        'Parrish',
        'Parsons',
        'Pate',
        'Patel',
        'Patrick',
        'Patterson',
        'Patton',
        'Paul',
        'Payne',
        'Pearson',
        'Peck',
        'Pena',
        'Pennington',
        'Perez',
        'Perkins',
        'Perry',
        'Peters',
        'Petersen',
        'Peterson',
        'Petty',
        'Phelps',
        'Phillips',
        'Pickett',
        'Pierce',
        'Pittman',
        'Pitts',
        'Pollard',
        'Poole',
        'Pope',
        'Porter',
        'Potter',
        'Potts',
        'Powell',
        'Powers',
        'Pratt',
        'Preston',
        'Price',
        'Prince',
        'Pruitt',
        'Puckett',
        'Pugh',
        'Quinn',
        'Ramirez',
        'Ramos',
        'Ramsey',
        'Randall',
        'Randolph',
        'Rasmussen',
        'Ratliff',
        'Ray',
        'Raymond',
        'Reed',
        'Reese',
        'Reeves',
        'Reid',
        'Reilly',
        'Reyes',
        'Reynolds',
        'Rhodes',
        'Rice',
        'Rich',
        'Richard',
        'Richards',
        'Richardson',
        'Richmond',
        'Riddle',
        'Riggs',
        'Riley',
        'Rios',
        'Rivas',
        'Rivera',
        'Rivers',
        'Roach',
        'Robbins',
        'Roberson',
        'Roberts',
        'Robertson',
        'Robinson',
        'Robles',
        'Rocha',
        'Rodgers',
        'Rodriguez',
        'Rodriquez',
        'Rogers',
        'Rojas',
        'Rollins',
        'Roman',
        'Romero',
        'Rosa',
        'Rosales',
        'Rosario',
        'Rose',
        'Ross',
        'Roth',
        'Rowe',
        'Rowland',
        'Roy',
        'Ruiz',
        'Rush',
        'Russell',
        'Russo',
        'Rutledge',
        'Ryan',
        'Salas',
        'Salazar',
        'Salinas',
        'Sampson',
        'Sanchez',
        'Sanders',
        'Sandoval',
        'Sanford',
        'Santana',
        'Santiago',
        'Santos',
        'Sargent',
        'Saunders',
        'Savage',
        'Sawyer',
        'Schmidt',
        'Schneider',
        'Schroeder',
        'Schultz',
        'Schwartz',
        'Scott',
        'Sears',
        'Sellers',
        'Serrano',
        'Sexton',
        'Shaffer',
        'Shannon',
        'Sharp',
        'Sharpe',
        'Shaw',
        'Shelton',
        'Shepard',
        'Shepherd',
        'Sheppard',
        'Sherman',
        'Shields',
        'Short',
        'Silva',
        'Simmons',
        'Simon',
        'Simpson',
        'Sims',
        'Singleton',
        'Skinner',
        'Slater',
        'Sloan',
        'Small',
        'Smith',
        'Snider',
        'Snow',
        'Snyder',
        'Solis',
        'Solomon',
        'Sosa',
        'Soto',
        'Sparks',
        'Spears',
        'Spence',
        'Spencer',
        'Stafford',
        'Stanley',
        'Stanton',
        'Stark',
        'Steele',
        'Stein',
        'Stephens',
        'Stephenson',
        'Stevens',
        'Stevenson',
        'Stewart',
        'Stokes',
        'Stone',
        'Stout',
        'Strickland',
        'Strong',
        'Stuart',
        'Suarez',
        'Sullivan',
        'Summers',
        'Sutton',
        'Swanson',
        'Sweeney',
        'Sweet',
        'Sykes',
        'Talley',
        'Tanner',
        'Tate',
        'Taylor',
        'Terrell',
        'Terry',
        'Thomas',
        'Thompson',
        'Thornton',
        'Tillman',
        'Todd',
        'Torres',
        'Townsend',
        'Tran',
        'Travis',
        'Trevino',
        'Trujillo',
        'Tucker',
        'Turner',
        'Tyler',
        'Tyson',
        'Underwood',
        'Valdez',
        'Valencia',
        'Valentine',
        'Valenzuela',
        'Vance',
        'Vang',
        'Vargas',
        'Vasquez',
        'Vaughan',
        'Vaughn',
        'Vazquez',
        'Vega',
        'Velasquez',
        'Velazquez',
        'Velez',
        'Villarreal',
        'Vincent',
        'Vinson',
        'Wade',
        'Wagner',
        'Walker',
        'Wall',
        'Wallace',
        'Waller',
        'Walls',
        'Walsh',
        'Walter',
        'Walters',
        'Walton',
        'Ward',
        'Ware',
        'Warner',
        'Warren',
        'Washington',
        'Waters',
        'Watkins',
        'Watson',
        'Watts',
        'Weaver',
        'Webb',
        'Weber',
        'Webster',
        'Weeks',
        'Weiss',
        'Welch',
        'Wells',
        'West',
        'Wheeler',
        'Whitaker',
        'White',
        'Whitehead',
        'Whitfield',
        'Whitley',
        'Whitney',
        'Wiggins',
        'Wilcox',
        'Wilder',
        'Wiley',
        'Wilkerson',
        'Wilkins',
        'Wilkinson',
        'William',
        'Williams',
        'Williamson',
        'Willis',
        'Wilson',
        'Winters',
        'Wise',
        'Witt',
        'Wolf',
        'Wolfe',
        'Wong',
        'Wood',
        'Woodard',
        'Woods',
        'Woodward',
        'Wooten',
        'Workman',
        'Wright',
        'Wyatt',
        'Wynn',
        'Yang',
        'Yates',
        'York',
        'Young',
        'Zamora',
        'Zimmerman');

    //43
    $array_school_name = array('Advanced Academy','Advantage Academy','Ahead of the Curve','Alphabet Kids','Amazing Alaska','Angel Wood University','Apple Valley School',
        'Aptitude Academy','Baby Stars','Bella Vista Institute','Bellwether High School','Better Change','Better Tomorrow','Big Pine College',
        'Big Pine Grammar School','Big Valley Academy','Big Valley Middle School','Big Valley School for Girls','Brain Train','Bright Beginnings','Bright Future','Bright Future Academy',
        'Bright Horizons','Bright House','Broad River University','Brookside','Brookside Academy','Build For Success','Camelot Kids','Canyon View School for Girls',
        'Central Technical School','Chalkboard Champions','Children First','Children’s Den','Classic Academy','Clear Lake School for Girls',
        'Compassion Academy','Coral Coast High School','Coral Springs University','Country Day School','Crawford High School','Cream de la Crème','Creating Champions');

    $array_suffix = array('','Jr.','Sr.');
    $array_academic = array(1,2,3,4);
    $array_semester = array(1,2);
    $array_academic_code = array('2017','2018','2019','2020');
    $array_semester_code = array('01','02');

    $array_genders = array('Male', 'Female');
    $array_civil_status = array('Single', 'Married');
    $array_employment_status = array('Full-Time','Part-Time', 'Temporary', 'Seasonal');
// BS 4arrays
    $array_bachelor = array('Bachelor of Elementary Education','Bachelor of Secondary Education','Bachelor of Technical Teacher Education','BS in Industrial Education');
    
    $array_years = array('1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990');
    include '../../controller/systemcore.php'; 
    $systemcore = new systemcore();




   
    for ($stresser = 0; $stresser <= 20; $stresser++) {

      
      $academic_year = $array_academic[rand(0, 3)];
      $semester = $array_semester[rand(0, 1)];
      
      $academic_year_code_i = $academic_year-1;
      $semester_code_i = $semester-1;

      // echo $academic_year_code_i;

      $academic_year_code = $array_academic_code[$academic_year_code_i];
      $semester_code = $array_semester_code[$semester_code_i];
      

      $first_name = $array_f_name[rand(0, 149)];
      $last_name = $array_last_names[rand(0, 999)];
      $middle_name = $array_last_names[rand(0, 999)];
      $suffix = $array_suffix[rand(0, 2)];
      $birthday = date('1991-01-01'); //------------------------
      $gender = $array_genders[rand(0, 1)];
      $civil_status = $array_civil_status[rand(0, 1)];
      $current_address = "Bago City";
      $address = "Bago City";
      $contact = "09123456789";
      $email = "example@email.com";
      
      $access = '7';//------------------------------
      $employment_status = $array_employment_status[rand(0, 3)];
      
      
      //
        $bachelor_name = array($array_school_name[rand(0, 40)]);
        $bachelor_course = array($array_bachelor[rand(0, 3)]);
        $bachelor_level = array('5');
        $bachelor_year_graduated = array($array_years[rand(0, 9)]);
  
        $master_name = array($array_school_name[rand(0, 40)]);
        $master_course = array($array_bachelor[rand(0, 3)]);
        $master_level = array('5');
        $master_year_graduated = array($array_years[rand(0, 9)]);
  
      
      //parent
        $parent_type = array('FATHER', 'MOTHER');
        $parent_first_name =  array($array_f_name[rand(0, 149)], $array_f_name[rand(0, 149)]);
        $parent_last_name = array($array_last_names[rand(0, 999)], $array_last_names[rand(0, 999)]);
        $parent_middle_name = array($array_last_names[rand(0, 999)], $array_last_names[rand(0, 999)]);
        $parent_suffix = array('', '');
        $parent_occupation = array('', '');
        $parent_anual_income = array('40000', '20000');
        $parent_contact_number = array('091234523', '0912345678');
  
      //primary school
      
      $primary_school_name = array($array_school_name[rand(0, 40)]);
      $primary_school_grade_level = array('4');
      $primary_school_year_graduated = array($array_years[rand(0, 9)]);
        //secondary 
      $secondary_name = array($array_school_name[rand(0, 40)]);
      $secondary_grade_level = array('4');
      $secondary_year_graduated = array($array_years[rand(0, 9)]);
        //senior
      $senior_name = array($array_school_name[rand(0, 40)]);
      $senior_strand = array('5');
      $senior_level = array('4');
      $senior_year_graduated = array($array_years[rand(0, 9)]);


      if($access == "7"){
        $count = 1;
        $SelectGroups = $systemcore->SelectTable("system_user WHERE access = '7'");
        if($SelectGroups != "none"){
          foreach($SelectGroups as $value){  
            $count++;
          }
        }
        $account_id = "P".sprintf("%04s", $count);
      }else{
        $count = 1;
        $SelectGroups = $systemcore->SelectTable("system_user WHERE access != '7' AND access != '6'");
        if($SelectGroups != "none"){
          foreach($SelectGroups as $value){  
            $count++;
          }
        }
        $account_id = "S".sprintf("%04s", $count);
      }
  
      $letters=array("A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z");
      $password = $letters[rand(0,49)].$letters[rand(0,49)].rand(10,99).$letters[rand(0,49)].$letters[rand(0,49)].rand(10,99);
      $password = md5($password);
  
      $table = "system_user";
      $table_col = "`account_id`, `academic_year_id`, `semester_id`, `first_name`, `middle_name`, `last_name`, `suffix`, `birthday`, `gender`, `username`, `password`, `address`, `contact`, `access`, `civil_status`, `current_address`, `email_address`, `employment_status`";
      $table_val = "'$account_id', '$academic_year', '$semester', '$first_name', '$middle_name', '$last_name', '$suffix', '$birthday', '$gender', '$account_id', '$password', '$address', '$contact', '$access', '$civil_status', '$current_address', '$email', '$employment_status'"; 
      $InsertTable = $systemcore->InsertTable($table, $table_col, $table_val);
  
      $length = count($bachelor_name);
      for ($x = 0; $x < $length; $x++) {
  
        $table = "system_staff_bachelor_school";
        $table_col = "`account_id`, `school_name`, `course`, `bachelor_level`, `year_graduated`";
        $table_val = "'$account_id', '$bachelor_name[$x]', '$bachelor_course[$x]', '$bachelor_level[$x]', '$bachelor_year_graduated[$x]'"; 
        $InsertTable = $systemcore->InsertTable($table, $table_col, $table_val);
      }
  
      $length = count($master_name);
      for ($x = 0; $x < $length; $x++) {
  
        $table = "system_staff_master_school";
        $table_col = "`account_id`, `school_name`, `course`, `master_level`, `year_graduated`";
        $table_val = "'$account_id', '$master_name[$x]', '$master_course[$x]', '$master_level[$x]', '$master_year_graduated[$x]'"; 
        $InsertTable = $systemcore->InsertTable($table, $table_col, $table_val);
      }
  
      $length = count($parent_first_name);
      for ($x = 0; $x < $length; $x++) {
  
        $table = "system_parent_info";
        $table_col = "`student_id`, `parent_type`, `first_name`, `middle_name`, `last_name`, `suffix`, `occupation`, `anual_income`, `contact_number`";
        $table_val = "'$account_id', '$parent_type[$x]', '$parent_first_name[$x]', '$parent_last_name[$x]', '$parent_middle_name[$x]', '$parent_suffix[$x]', '$parent_occupation[$x]', '$parent_anual_income[$x]', '$parent_contact_number[$x]'"; 
        $InsertTable = $systemcore->InsertTable($table, $table_col, $table_val);
      }
  
      $length = count($primary_school_name);
      for ($x = 0; $x < $length; $x++) {
  
        $table = "system_student_primary_school";
        $table_col = "`student_id`, `school_name`, `primary_level`, `year_graduated`";
        $table_val = "'$account_id', '$primary_school_name[$x]', '$primary_school_grade_level[$x]', '$primary_school_year_graduated[$x]'"; 
        $InsertTable = $systemcore->InsertTable($table, $table_col, $table_val);
      }
  
      $length = count($secondary_name);
      for ($x = 0; $x < $length; $x++) {
  
        $table = "system_student_secondary_school";
        $table_col = "`student_id`, `school_name`, `secondary_level`, `year_graduated`";
        $table_val = "'$account_id', '$secondary_name[$x]', '$secondary_grade_level[$x]', '$secondary_year_graduated[$x]'"; 
        $InsertTable = $systemcore->InsertTable($table, $table_col, $table_val);
      }
  
      $length = count($senior_name);
      for ($x = 0; $x < $length; $x++) {
  
        $table = "system_student_senior_secondary";
        $table_col = "`student_id`, `school_name`, `senior_strand`, `senior_level`, `year_graduated`";
        $table_val = "'$account_id', '$senior_name[$x]', '$senior_strand[$x]', '$senior_level[$x]', '$senior_year_graduated[$x]'"; 
        $InsertTable = $systemcore->InsertTable($table, $table_col, $table_val);
      }
  
  }